name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: education/autograding@v1
        id: autograding
        with:
          points: 10
      - name: Install pytest
        run: pip install pytest
      - name: Run tests
        run: pytest
        id: tests
      - name: Report results
        uses: education/autograding/actions/reporter@v1
        with:
          test-results: "${{ steps.tests.outputs.results }}"
