name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Autograding
        uses: education/autograding@v1
        id: autograding
        with:
          points: 10
          
      - name: Install pytest
        run: pip install pytest
        
      - name: Run tests
        run: pytest --json-report
        id: tests
        continue-on-error: true
        
      - name: Report results
        uses: classroom-resources/autograding-reporter@v1
        with:
          test-results: "${{ steps.tests.outputs.report }}"
          token: ${{ secrets.GITHUB_TOKEN }}
